@CleanTeeth.API_HostAddress = http://localhost:4554/api/appointments

GET {{CleanTeeth.API_HostAddress}}
ACCEPT: application/json
###
GET {{CleanTeeth.API_HostAddress}}/019eb0ac-f297-7cde-845d-36f84c0c558f
ACCEPT: application/json

###
POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json
{
  "patientId":"019e890b-ba0e-786f-8a00-89d86e247a01",
  "dentistId":"019e9e7c-51f3-7e5c-8dd3-2b27467ad066",
  "dentalOfficeId":"019e63b6-a2eb-7987-af46-af05ac4224e5",
  "startDate":"2027-11-01T09:30:00",
  "endDate":"2027-11-01T11:30:00"

}

###
POST {{CleanTeeth.API_HostAddress}}/019EB59B-CC21-74F2-B479-499A43DFFFFE/complete

###
POST {{CleanTeeth.API_HostAddress}}/019eb0ac-f297-7cde-845d-36f84c0c558f/cancel

###
DELETE {{CleanTeeth.API_HostAddress}}/019e7a57-4d6f-7a4e-ac73-b4ba0840b4f9
