@CleanTeeth.API_HostAddress = http://localhost:5104/api/appointments

GET {{CleanTeeth.API_HostAddress}}
ACCEPT: application/json
###
GET {{CleanTeeth.API_HostAddress}}/019EB0AC-F297-7CDE-845D-36F84C0C558F
ACCEPT: application/json

###
POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json
{
  "patientId":"019e9235-fe7b-7757-b9ab-d0836d5664aa",
  "dentistId":"019e9e7c-51f3-7e5c-8dd3-2b27467ad066",
  "dentalOfficeId":"019e63b6-a2eb-7987-af46-af05ac4224e5",
  "startDate":"2027-10-01T09:30:00",
  "endDate":"2027-10-01T11:30:00"

}

###
PUT {{CleanTeeth.API_HostAddress}}/019e63b6-a2eb-7987-af46-af05ac4224e5
Content-Type: application/json
{
  "name":"Dental Office CCC"
}
###
DELETE {{CleanTeeth.API_HostAddress}}/019e7a57-4d6f-7a4e-ac73-b4ba0840b4f9
