@CleanTeeth.API_HostAddress = http://localhost:4554/api/Dentists

GET {{CleanTeeth.API_HostAddress}}?page=1&recordsPerPage=10
ACCEPT: application/json
###
GET {{CleanTeeth.API_HostAddress}}/019e9e7c-51f3-7e5c-8dd3-2b27467ad066
ACCEPT: application/json

###
POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json
{
  "name":"Dr.Mojtaba Pashmaki",
  "email":"pashmak@gmail.com"
}

###
PUT {{CleanTeeth.API_HostAddress}}/019ea653-e459-7a65-a6c4-25468e0eddd7
Content-Type: application/json
{
  "name":"Mojtaba Pashmakabadi",
  "email":"pashmakabadi@gmail.com"
}
###
DELETE {{CleanTeeth.API_HostAddress}}/019ea625-7bd2-7513-8289-498384b4a2f9
