@CleanTeeth.API_HostAddress = https://localhost:7118/api/Dentists

GET {{CleanTeeth.API_HostAddress}}?page=1&recordsPerPage=10
ACCEPT: application/json
###
GET {{CleanTeeth.API_HostAddress}}/019e9e7c-51f3-7e5c-8dd3-2b27467ad066
ACCEPT: application/json

###
POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json
{
  "name":"Dr.Hasan Poshtaki",
  "email":"poshtaki@gmail.com"
}

###
PUT {{CleanTeeth.API_HostAddress}}/019EC04B-712E-70FB-A237-A7A24892AB1F
Content-Type: application/json
{
  "name":"Dr.Hasan Poshtakabadi",
  "email":"poshtaki@gmail.com"
}
###
DELETE {{CleanTeeth.API_HostAddress}}/019ea625-7bd2-7513-8289-498384b4a2f9
