@CleanTeeth.API_HostAddress = http://localhost:5104/api/patients

GET {{CleanTeeth.API_HostAddress}}?page=1&recordsPerPage=10&email=em
ACCEPT: application/json
###
GET {{CleanTeeth.API_HostAddress}}/019e9235-fe7b-7757-b9ab-d0836d5664aa
ACCEPT: application/json

###
POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json
{
  "name":"Mohsen Zarei",
  "email":"Moh@gmail.com"
}

###
PUT {{CleanTeeth.API_HostAddress}}/019e63b6-a2eb-7987-af46-af05ac4224e5
Content-Type: application/json
{
  "name":"Dental Office CCC"
}
###
DELETE {{CleanTeeth.API_HostAddress}}/019e7a57-4d6f-7a4e-ac73-b4ba0840b4f9
